### ISSUE TITLE
LOFO as a SelectionMethod

### ISSUE THREAD

**Issue by aerdem4** [fidelity/selective#2]
Adding [LOFO](https://github.com/aerdem4/lofo-importance) as a SelectionMethod can create a validation-scheme dependent feature importance alternative. LOFO doesn't have any large dependencies and should be usable with a few lines of code. I would be happy to help if you need.

**Comment by skadio** [comment]
Based on this recommendation, we included a cross-validation scheme (not exactly LOFO) that allows validation for all selector methods. Thanks again for the collaboration!
